name: Deploy to GitHub Releases
on:   
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy-to-github-releases:
    runs-on: windows-latest
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Version
        id: version
        run: |
          echo $GITHUB_WORKSPACE
          
          # Get the current date
          $DATE = Get-Date -Format "yyyy.Mdd"

          # Get the current hour and minute without leading zero for the hour
          # Get the current hour and minute
          $HOUR = [int](Get-Date -Format "HH") # Convert hour to integer to strip any leading zero
      
          # If the hour is 0 (midnight), set it to an empty string
          if ($HOUR -eq 0) {
            $HOUR = ''
          }
                
          $MINUTE = Get-Date -Format "mm" # Keep minutes as-is
      
          # Construct the time, omitting hour if it's empty
          $TIME = "$HOUR$MINUTE"
          
          # Construct the version using DATE and TIME
          $VERSION = "$DATE.$TIME"
          Write-Output "Generated version: $VERSION"
          # Export version as an output
          echo "version=$VERSION" >> $env:GITHUB_OUTPUT
      - name: Version - Update project files
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: ".\\HvergiToolkit\\HvergiToolkit.csproj"
          version: ${{ steps.version.outputs.version }}
      - name: Environment - Build Number
        uses: myci-actions/export-env-var@1
        with:
          name: BUILD_NUMBER
          value: ${{ steps.version.outputs.version }}
      - name: .NET - Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: .NET - Publish
        shell: pwsh
        run: |
          Write-Output "Version: ${{ steps.version.outputs.version }}"
          dotnet publish HvergiToolkit/HvergiToolkit.csproj -c Release -o ./Publish -r win-x64 --framework net9.0-windows10.0.19041.0 --self-contained true
      - name: Velopack
        shell: pwsh
        run: |
          Write-Output "Version: ${{ steps.version.outputs.version }}"

          dotnet tool install -g vpk
          vpk download github --repoUrl https://github.com/hvergi/HvergiToolkit
          vpk pack -u HvergiToolkit -v ${{ steps.version.outputs.version }} -p Publish
          vpk upload github --repoUrl https://github.com/hvergi/HvergiToolkit --publish --releaseName "HvergiToolkit v${{ steps.version.outputs.version }}" --tag v${{ steps.version.outputs.version }} --token ${{ secrets.GITHUB_TOKEN }}
