name: Deploy to GitHub Releases
on: workflow_dispatch
permissions:
  contents: write
jobs:
  deploy-to-github-releases:
    runs-on: windows-latest
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Version
        id: version
        run: |
          echo $GITHUB_WORKSPACE
          dir $GITHUB_WORKSPACE
          # Get the current date
          $DATE = Get-Date -Format "yyyy.Mdd"

          # Get the current hour and minute without leading zero for the hour
          # Get the current hour and minute
          $HOUR = [int](Get-Date -Format "HH") # Convert hour to integer to strip any leading zero
      
          # If the hour is 0 (midnight), set it to an empty string
          if ($HOUR -eq 0) {
            $HOUR = ''
          }
                
          $MINUTE = Get-Date -Format "mm" # Keep minutes as-is
      
          # Construct the time, omitting hour if it's empty
          $TIME = "$HOUR$MINUTE"
          
          # Construct the version using DATE and TIME
          $VERSION = "$DATE.$TIME"
          Write-Output "Generated version: $VERSION"

          # Export version as an output
          echo "version=$VERSION" >> $env:GITHUB_OUTPUT
      
